Gian/event camera
uzh-rpg/flightmare_unity pull request #3
Opened 2021-02-28 23:31 UTC by gerni17

2021-02-28 23:40 UTC, gerni17 commented
This is the unity side containing the event camera: the main difference is that it works in gamma color space everything else should be the same.

2021-03-20 21:59 UTC, slimeth commented
@gerni17 would it be hard to change to linear color space? or why did you choose gamma color space? Also, could you change the pull request to merge into the branch **dev/flightmare-release**, which is the up-to-date developing branch, instead of the main branch?

2021-03-26 17:53 UTC, gerni17 commented
It would not be hard to change to linear, but the event camera does not properly work in it. The resulting scene of the eventcamera is different than the RGB cameras output.

2021-03-28 09:20 UTC, slimeth commented
@yun-long what do you think?

2021-03-28 10:22 UTC, slimeth requested changes
review first part

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +      // video_client_port=10271;
not needed anymore, right?

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +      // Debug.LogError("Update: " + Time.deltaTime);
should this really be an error log?

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> -          currentCam.farClipPlane = camera.farClipPlane[0];
please add this again

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +        // always activate vehcile cam
why do you want it always?

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +        // always activate vehcile cam
would always use one targetwindow and their number is limited.

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +            // Debug.Log(quaternion.eulerAngles);
either delete or uncomment

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +        // always activate vehcile cam
also removes the feature to switch between cameras.

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +        vehicleCollider.enabled = false;
weird formatting

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +            Debug.Log("settins width and height " + settings.camHeight + "/" + settings.camWidth);
necessary debug message?

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +            //     settings.camWidth, settings.camHeight);
why commenting default settings? the user might have defined different settings then the RPG default settings

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +                    img_post_processing.image_modes[layer_id], camera.fov, currentCam);
add clipping planes

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> +    byte[] readImageFromHiddenCamera(Camera subcam, EventCamera_t cam_config)
maybe rename to readImageFromHiddenEventCamera? Same name lead to brief confusion

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> -    public void ButtonPointCloud()
please add point cloud feature again

2021-03-28 10:22 UTC, slimeth commented on Assets/Flightmare/Scripts/CameraController.cs
> -// backup code. -----
@yun-long do you still need the backup code?

2021-04-05 12:35 UTC, gerni17 commented on Assets/Flightmare/Scripts/RPGImageSynthesis.cs
> +    int target_display = 3;
I don't remember exactly why 3, I think that this can be changed and that it was chosen because the previous displays were already used for other cameras.

2021-04-05 12:37 UTC, gerni17 commented on Assets/Flightmare/Scripts/RPGImageSynthesis.cs
> +      string image_mode = "optical_flow";
because this is a pure OF camera:CreateHidden**OF**Camera

2021-04-05 13:04 UTC, gerni17 commented on Assets/Flightmare/Scripts/RPGImageSynthesis.cs
> +      addOFCamera(newCamera, image_mode);
this is ust for the OF camera, I am not sure whther I understand what you are saying

2021-04-05 13:06 UTC, gerni17 commented on Assets/Flightmare/Scripts/RPGImageSynthesis.cs
> +      RenderTexture.ReleaseTemporary(renderRT);
I must admit that I do not remember exactly but the last release is to release it definitely after rendering, wheras the other is just some rescaling option

2021-04-05 13:07 UTC, gerni17 commented on Assets/Flightmare/Scripts/CameraController.cs
> -    public GameObject PointCloudSaved;
I never used it and it was not working when I started to work on it...

2021-04-05 13:11 UTC, gerni17 commented on Assets/Flightmare/Scripts/CameraController.cs
> -      StartCoroutine(WaitForRender());
this was because the coroutine was rendering twice at the same position.

2021-04-05 13:13 UTC, gerni17 commented on Assets/Flightmare/Scripts/CameraController.cs
> +        // always activate vehcile cam
ok, I put it back in place

2021-04-06 08:11 UTC, merged